### ISSUE TITLE
BIRD not receiving ExaBGP routes

### ISSUE THREAD

**Issue by rsingha108** [ncatelli/bird_examples_docker#5]
I am trying to peer a BIRD with two ExaBGP as shown : 
![bird-topo drawio](https://user-images.githubusercontent.com/97200032/227860075-4f4248ec-992f-40e2-8909-935c557b4c72.png)

Peer1 (BIRD) config:
```
#router id 10.0.0.10;

protocol kernel {
  metric 0;
  import none;
  learn;
  export all;
}
protocol device {
}
protocol direct {
}
protocol bgp peer2 {
  local as 43617;
  neighbor 7.0.0.3 as 43618;
  import all;
  export all;
}
protocol bgp peer3 {
  local as 43617;
  neighbor 3.0.0.3 as 43619;
  import all;
  export all;
}

```

Peer 2 (ExaBGP) config:
```
process announce-routes{
    run python exabgp/example.py;
    encoder json;
}

neighbor 7.0.0.2 {                 # Remote neighbor to peer with
    router-id 7.0.0.3;              # Our local router-id
    local-address 7.0.0.3;          # Our local update-source
    local-as 43618;                    # Our local AS
    peer-as 43617;                     # Peer's AS

    api {
        processes [announce-routes];
    }
}
```

Peer 3 (ExaBGP) config:
```
process announce-routes {
    run python exabgp/example.py;
    encoder json;
}

neighbor 3.0.0.2 {                 # Remote neighbor to peer with
    router-id 3.0.0.3;              # Our local router-id
    local-address 3.0.0.3;          # Our local update-source
    local-as 43619;                    # Our local AS
    peer-as 43617;                     # Peer's AS

    api {
        processes [announce-routes];
    }
}
```

docker-compose.yaml:

```
version: '3'
services:

  peer1:
    build : .
    hostname: peer1
    privileged: true
    volumes:
      - ./conf/peer1/etc/bird:/etc/bird
    networks:
      peeringbr1:
        ipv4_address: 7.0.0.2
      peeringbr2:
        ipv4_address: 3.0.0.2
        
  peer2:
    image: "mikenowak/exabgp:latest"
    hostname: peer2
    privileged: true
    volumes:
      - ./conf/peer2/etc/exabgp:/exabgp
    networks:
      peeringbr1:
        ipv4_address: 7.0.0.3
    entrypoint: tail -f /dev/null 
    
    
  peer3:
    image: "mikenowak/exabgp:latest"
    hostname: peer3
    privileged: true
    volumes:
      - ./conf/peer3/etc/exabgp:/exabgp
    networks:
      peeringbr2:
        ipv4_address: 3.0.0.3
    entrypoint: tail -f /dev/null 
    

networks:
  peeringbr1:
    driver: bridge
    ipam:
     config:
       - subnet: '7.0.0.0/24'
  peeringbr2:
    driver: bridge
    ipam:
     config:
       - subnet: '3.0.0.0/24'
```

When I do "birdc show route" it is not showing the routes advertised by ExaBGP. Did I make any mistake?

Note: This same config was working before I upgraded docker-compose. After upgrading, it's not working.
